apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend-deployment
  labels:
    app: notes-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-frontend
  template:
    metadata:
      labels:
        app: notes-frontend
    spec:
      containers:
        - name: notes-frontend
          image: mohamedessam1911/notes-frontend:latest
          ports:
            - containerPort: 3000

